### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by waplet** [alphp/strftime#21]
https://github.com/alphp/strftime/blob/master/src/php-8.1-strftime.php#L43C5-L43C76

When passing Carbon aka DateTime object to this strftime which has it's own timezone, it will always be formatted in the "default" server timezone?

Why is this overridden? 
Normally when it would have initiated from an "integer" it would have already have "default" timezone?!

**Comment by alphp** [comment]
Fixed in https://github.com/alphp/strftime/releases/tag/0.7.5

**Comment by waplet** [comment]
So with the "expectations" of the "TimeZone" to be used, it actually breaks the "polyfill" idea of being identical replacement for strftime. Because strftime only worked with the "date_default_timezone_get()". Most likely this tag should be "avoided" and/or removed.  as it leads to different behavior of how PHP acted before.

It would be correct approach,, but we are here not to fix PHP implementation.
Turns out "new DateTime()" in system is also always created with GMT+0 instead of date_default_timezone_get() and other issues, with php date functions.

cc: @alphp

**Comment by alphp** [comment]
The original signature of the strftime function is as follows:
```php
strftime(string $format, ?int $timestamp = null): string|false
```
Supporting $timestamp to be a DateTimeInterface is already a significant change.
The change made does not break backwards compatibility because strftime was not called with a DateTime object.
