### ISSUE TITLE
Minimum PHP version in composer.json is incorrect

### ISSUE THREAD

**Issue by IMSoP** [alphp/strftime#6]
Currently, the composer.json lists a minimum PHP version of 5.6, but the actual code includes many features which require later versions, such as a type declaration of `?string`, which is only valid since PHP 7.1

Either the documented minimum version should be updated, or the code changed to run on older versions.

**Comment by IMSoP** [comment]
By the way, thanks for making this repo, and I love the use of Basque as a test locale!

**Comment by alphp** [comment]
Thanks a lot
